/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/pngtest.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kylast_logo.geometry}
        material={materials["Kylast logo"]}
        position={[0, 0, -3]}
        rotation={[Math.PI / 2, 0, -Math.PI / 8]}
        scale={3.66}
      />
    </group>
  );
}

useGLTF.preload("/pngtest.glb");
